### ISSUE TITLE
[FR] text rendering along polygons borders

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#177]
As discussed in another issue it would be nice to be able to use ```text-placement: line;``` for polygon text drawing.
A simple example is mapbox terrain source. Contours are represented using polygons and thus for now it is impossible to use ```text-placement: line;``` to correctly render contours elevation.

**Comment by mtehver** [comment]
Thanks, SDK 4.1.2RC2 should fix the issue.

I am closing this for now, the issue can be reopened if needed.

**Comment by farfromrefug** [comment]
@mtehver i do see the text but there are drawn weirdly. 
Here are a few screenshots so you can see. Still testing with mapbox terrain source.
![screenshot_20180206-120616](https://user-images.githubusercontent.com/655344/35856541-a034434e-0b36-11e8-952a-2692e5e49ed1.png)
![screenshot_20180206-120858](https://user-images.githubusercontent.com/655344/35856542-a053c00c-0b36-11e8-9698-c00d531279ff.png)
![screenshot_20180206-120911](https://user-images.githubusercontent.com/655344/35856543-a079d256-0b36-11e8-9b69-5261c73e8594.png)

**Comment by mtehver** [comment]
@farfromrefug I think I understand what is going on - the contour polygons are clipped against tile boundaries which results in straight lines at the boundaries. For rendering polygons or lines this works ok, as long as small buffers around the boundaries are used (I guess MapBox does this). Texts are unfortunately rendered differently in the Carto SDK and there is no option currently to force text clipping at exact tile boundaries.

I am labelling this currently as 'no fix planned' due to non-trivial technical complexity. But I am keeping the issue open.

@jaakla What is the status of OMT countour data? I would recommend using OMT contours anyway, due to potential service term issues when using MapBox tiles outside of MapBox SDKs.

**Comment by farfromrefug** [comment]
@jaakla thanks for clarifying. Sadly using it within a free and open source project, i can't really afford OMT premium subscription.
Might look at providing it from my own server.

Thanks @mtehver for looking into this.

**Comment by mtehver** [comment]
@farfromrefug I think I found a workaround for this issue, by removing all polygon edges that are strictly outside of the tile. Assuming MapBox adds buffers to contours, this should work. I think we will include the fix in the official 4.1.2 release.

**Comment by farfromrefug** [comment]
@mtehver that would be so awesome, really!!!
I will test it as soon as it's released.
Thanks again
