### ISSUE TITLE
hiding the watermark

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#236]
I was wondering what was the rule on the watermark and if there was a way to hide it.
I mean it is related to the use of the APIs so is there a way to hide it if only using external data like OSM?
If I fork the framework, can I hide it?

I am wondering for the use of the carto sdk within open source free apps.

Thanks

**Comment by mtehver** [comment]
Technically, yes you can hide the watermark if you compile the SDK yourself. And if you use your own datasources and do not connect to CARTO services, then we have no issues with that.

There is a small module that is actually missing from the Open Source part of the SDK (and is not required for most part), it is called 'license manager'. It is needed to use `CartoOnlineVectorTileLayer` (and most other classes with Carto-prefix). If you are fine with using OpenMapTiles service provider directly, then that is probably the way to go - use your own build of the SDK.

Otherwise, if you want to keep using CARTO online services but without watermark, you will need to negotiate this with CARTO sales.

**Comment by farfromrefug** [comment]
@mtehver thanks for the explanation. Just so we are clear I don't want not to use the Carto SDK itself and I fully understand how much work you put into this. 
Just the watermark is quite big(twice as big as Mapbox one) and can really be an issue in some layout.

Also I really love your implementation in the sense that everything is possible. And I am thinking of starting a fork that could be used by OSM or other FOSS projects.

For my personal open source project I would to keep your version because I want carto features like packages download. Maybe you could make the watermark a little smaller ;)

**Comment by jaakla** [comment]
Good point, we’ll review it

**Comment by mtehver** [comment]
Actually after looking at the code and scratching my head it seems that we allow this even now (if you have a valid API key from CARTO):

`mapView.getOptions().setWatermarkScale(0.5f)`
