### ISSUE TITLE
[cartocss] shield and dpi

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#305]
Is there a way to make my shield images look sharper on high dpi devices?
Right now it looks really blurry
![Screenshot_20190729-145917_Cairn_Mobile](https://user-images.githubusercontent.com/655344/62050446-865de780-b211-11e9-91c0-39aa5bd982bd.png)

**Comment by mtehver** [comment]
@farfromrefug Are your shield images raster files or SVG files? SVG files are internally converted to high-DPI images and should look sharp. For raster shield there is currently no option to define image scaling, I am afraid. A possible workaround is to use 'text' and 'marker' symbolizers instead of 'shield' symbolizers. 'marker' symbolizer supports `marker-width` and `marker-height` attributes.

**Comment by farfromrefug** [comment]
@mtehver right now it is a bitmap. I can use a SVG. 
But i guess it would be "faster" to use text and marker as you said as it does not need to convert SVG to bitmap, right?

Thanks!

**Comment by mtehver** [comment]
@farfromrefug The SVG is converted only once and 'on demand' (only when a tile references it), so it should be fast enough. 

My original suggestion may not actually work if your shield bitmaps and texts overlap, as in that case either bitmap or text will not be shown if 2 separate CartoCSS symbolizers are used.

**Comment by farfromrefug** [comment]
@mtehver it works for me for now. And i actually like the fact that the texts! can get hidden on overlap while the icon still being visible.

Thanks!
