### ISSUE TITLE
Layer unique id

### ISSUE THREAD

**Issue by gisman82** [CartoDB/mobile-sdk#336]
A layer should have an unique id to identify a specific layer. Eg. When a vector element is clicked. Maybe even a kind of hash map to store other informations.
As the native api on android is not returning an inherited object.

**Comment by mtehver** [comment]
Correct, each time a layer is queried from vector element click info, a new instance of the 'layer' is created. To be more specific, a new lightweight wrapper pointing to the layer object on the native side is created. Fortunately it is possible to compare layer instances by using `equals` method instead of `==` operator.

Nevertheless, metadata or tag support for layers is probably a good idea. I will mark the issue as 'idea-maybe-future' tag.

**Comment by mtehver** [comment]
The API for this is now implemented in SDK 4.3.0RC1.

**Comment by mtehver** [comment]
SDK 4.3.0 is released now. Thus closing this.
