### ISSUE TITLE
css marker clipped by tiles

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#343]
It seems markers defined in css for vector tiles are clipped by tiles limit.
I can clearly see that by zooming in and out
![Simulator Screen Shot - iPhone 6 - 2020-03-21 at 09 19 15](https://user-images.githubusercontent.com/655344/77222690-c7668b80-6b55-11ea-9846-dc8ae4ae053f.png)

**Comment by mtehver** [comment]
A little background on this issue. There are 2 rendering modes for points/markers/texts: 'label' mode and 'simple' mode. By default this mode is controlled by 2 parameters 'allow-overlap' and 'clip'. If 'clip' is not defined, then 'allow-overlap' is used implicitly as 'clip' value. If 'clip' is set to false, then 'label' rendering mode is used.  Otherwise 'simple' mode is used.

Label rendering mode thus does no clipping at tile boundaries and supports overlap detection and line geometry but is quite costly. Both memory wise and performance wise. It does not scale over 10,000 features. Label mode also requires unique feature ids to work properly. Labels are never clipped at tile borders.

Simple mode does not support overlap detection nor other label features but is very low cost and scales to 100,000 features and above. Simple mode features are always clipped at tile borders.

Regarding this specific example, using

```
marker-allow-overlap: true;
marker-clip: false;
```

should make this work.

**Comment by farfromrefug** [comment]
@mtehver awesome explaination! That should be in carto css notes!
thanks!
