### ISSUE TITLE
CartoCSS Text Zoom (4.2.0)

### ISSUE THREAD

**Issue by lasyakoechlin** [CartoDB/mobile-sdk#366]
Hi, I am using v4.2.0 and I am trying to make text which disappears as the zoom changes.

Here is my CartoCSS code

```
#text_labels {
	text-name: @name;
	text-orientation: [rotation];
	text-fill: @text_fill;
	text-face-name: @medium;
	text-size: linear([view::zoom], (15, 0), (15.5, 5), (17, 7), (20, 14));
}
```

I have also tried `#text_labels [zoom >= 15] { ... }`

My expectation is that for zooms < 15, the text should be invisible but that doesn't seem to be working.

I tried adding the following modification: `text-fill: ( zoom > 15 ? @text_fill : rgba(0,0,0,0) ) ;` but now the text does not appear at all.

When I tried `text-fill: ( [view::zoom] > 15 ? @text_fill : rgba(0,0,0,0) ) ;` then the text appeared at all levels

Thanks for your help

**Comment by mtehver** [comment]
@lasyakoechlin I did a quick test with SDK 4.3.0 of the expression `text-size: linear([view::zoom], (15, 0), (15.5, 5), (17, 7), (20, 14));` and it definitely worked as expected, the same with `text-fill: ( [view::zoom] > 15 ? @text_fill : rgba(0,0,0,0) ) ;`.

Also, instead of `text-fill: ( zoom > 15 ? @text_fill : rgba(0,0,0,0) ) ;` you should use `text-fill: ( [zoom] > 15 ? @text_fill : rgba(0,0,0,0) ) ;`

If you have a minisample that demonstrates the issue, I could take a look at this.

**Comment by lasyakoechlin** [comment]
Thanks for the feedback. I guess I will have to try 4.3.0. I have been avoiding updating due to the increased SDK size.
