### ISSUE TITLE
GeoJSONGeometryReader readFeatureCollection handling wrong geometries

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#441]
I stumbled upon the case of an API returning some wrong features geometry(empty ones) in a featurecollection. I have no easy solution to "filter" those from the return of the API (seeing my env parsing the JSON first to filter, i would need to stringify it again after to pass it to Carto for it to parse it again, would be dead slow).
So i changed the sdk to catch the parsing error for each failing feature and just continue. I end up with a working feature collection of only correctly parsed features.

Would you agree for a PR which adds an optional parameter to `readFeatureCollection` which would be something like `ignoreParseErrors` (default to false) ?

**Comment by mtehver** [comment]
Can you give an example of a feature that is not accepted? I looked into https://datatracker.ietf.org/doc/html/rfc7946 and it seems there are a few cases when valid GeoJSON is not accepted by the SDK. I will look into it.

**Comment by farfromrefug** [comment]
@mtehver the API i use returns "empty" geometry objects. They dont respect the specs!. But seeing the size of the return object i cant handle it before passing it to Carto.
This is the api call https://data.mobilites-m.fr/api/lines/json?types=ligne

**Comment by mtehver** [comment]
Ok, you are correct. This output is really illegal according to RFC7946. If they had used 'null' for geometry instead of '{}', then it would have been valid.

I understand the performance concern, but I do not think SDK should accept illegal input in that case. A simple, but fast and ugly hack would be to simply do regex replacement `s/"geometry":\s*{\s*}/"geometry":null/` before passing the JSON to the SDK. Note that you need to checkout the latest `GeoJSONGeometryReader` for this to work, as older version did not accept null geometry.

**Comment by farfromrefug** [comment]
@mtehver yes you are right this would work. In my fork i trapped the parsing error and continue. I understand your point about only supporting the specs. I ll go the replace route. Thanks!
